spring:
  redis:
    host: 127.0.0.1
    port: 6379
  datasource:
    url: jdbc:h2:mem:account
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true # resource/*.sql 파일을 자동으로 넣어주는 옵션 
    database-platform: H2
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        "[format_sql]": true
        "[show_sql]": true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER